pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
               git branch: 'main', url: 'https://github.com/Chaitanya0311/pipeline-build.git'
            }
        }
        stage('Build') {
            steps {
               sh 'mvn clean install'
            }
        }
    }
}
