pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
               git 'https://github.com/Chaitanya0311/docker-hello-world-spring-boot.git'
            }
        }
        stage('Build') {
            steps {
               sh 'mvn clean install'
            }
        }
    }
}
